# Generated by Django 4.2.5 on 2023-10-04 06:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("webchat", "0003_privatemessage_receiver_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="privatemessage",
            name="conversation",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="messages",
                to="webchat.privateconversation",
            ),
        ),
    ]
