# Generated by Django 4.2.5 on 2023-10-10 15:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("webchat", "0004_alter_privatemessage_conversation"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="privateconversation",
            unique_together=set(),
        ),
    ]
