# Generated by Django 4.2.5 on 2023-10-14 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("webchat", "0006_alter_privateconversation_unique_together"),
    ]

    operations = [
        migrations.AddField(
            model_name="conversation",
            name="last_updated",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
