# Generated by Django 4.2.5 on 2023-10-14 05:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("webchat", "0006_alter_privateconversation_unique_together"),
        ("groups", "0003_alter_group_conversation_alter_group_owner"),
    ]

    operations = [
        migrations.AlterField(
            model_name="group",
            name="conversation",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="group",
                to="webchat.conversation",
            ),
        ),
    ]
