# Generated by Django 4.2.5 on 2023-09-27 15:35

import account.models
import account.validators
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0005_alter_user_is_superuser"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="userprofile",
            name="is_premium",
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="about_me",
            field=models.TextField(max_length=1000),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="cover_pic",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to=account.models.cover_pic_upload_path,
                validators=[account.validators.validate_image_file_exstension],
            ),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="friends",
            field=models.ManyToManyField(
                blank=True, related_name="friends", to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="profile_pic",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to=account.models.profile_pic_upload_path,
                validators=[account.validators.validate_image_file_exstension],
            ),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="user",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
