# Generated by Django 4.2.5 on 2023-10-17 17:48

import account.models
import account.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0008_alter_userprofile_user"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userprofile",
            name="profile_pic",
            field=models.ImageField(
                blank=True,
                default="profile/profile_pics/default_profile.jpg",
                null=True,
                upload_to=account.models.profile_pic_upload_path,
                validators=[account.validators.validate_image_file_exstension],
            ),
        ),
    ]
